import {
  LayoutGrid,
  BarChart3,
  Terminal,
  Users,
  Sparkles,
  Database,
  ShoppingCart,
  Video,
  KeyRound,
  ShieldCheck,
  Cloud,
  Activity,
  Megaphone,
  type LucideIcon,
} from "lucide-react";

export const categoryIconMap: Record<string, LucideIcon> = {
  "layout-grid": LayoutGrid,
  "bar-chart-3": BarChart3,
  terminal: Terminal,
  users: Users,
  sparkles: Sparkles,
  database: Database,
  "shopping-cart": ShoppingCart,
  video: Video,
  "key-round": KeyRound,
  "shield-check": ShieldCheck,
  cloud: Cloud,
  activity: Activity,
  megaphone: Megaphone,
};
