import { randomBytes } from "crypto";
import type { StackMergeToolSummary } from "@/lib/stack-merge";

const PLACEHOLDER_RE = /change-me[A-Za-z0-9-]*/g;

/**
 * Sustituye cada placeholder `change-me...` del compose fusionado por un
 * secreto aleatorio real, generado en el servidor por request (nunca se
 * reutiliza entre peticiones). Mismo placeholder → mismo secreto dentro de
 * un mismo archivo, para que sigan coincidiendo los pares tipo
 * "POSTGRES_PASSWORD=change-me-db-password # must match DB_..._PASSWORD
 * above" que ya usa el catálogo — igual que el randomizador del cliente en
 * docker-compose-block.tsx, pero aquí con `crypto` de Node porque este
 * módulo solo se ejecuta en el servidor.
 */
export function randomizeSecrets(yaml: string): string {
  const generated = new Map<string, string>();
  return yaml.replace(PLACEHOLDER_RE, (match) => {
    if (!generated.has(match)) generated.set(match, randomBytes(24).toString("hex").slice(0, 32));
    return generated.get(match)!;
  });
}

/** Un delimitador de heredoc que no aparece como línea suelta dentro del propio YAML, por seguridad en profundidad. */
function pickHeredocDelimiter(yaml: string): string {
  let delimiter = "ALTFREESTACK_COMPOSE_EOF";
  const lines = new Set(yaml.split("\n"));
  let suffix = 2;
  while (lines.has(delimiter)) delimiter = `ALTFREESTACK_COMPOSE_EOF_${suffix++}`;
  return delimiter;
}

interface DeployScriptStrings {
  header: string[];
  composeHeader: (names: string) => string[];
  alreadyExists: (dir: string) => string;
  alreadyExistsHint: (dir: string) => string;
  checkingDocker: string;
  startingContainers: string;
  successBanner: string;
  filesSavedAt: string;
  notIncluded: string;
}

const STRINGS: Record<"es" | "en", DeployScriptStrings> = {
  es: {
    header: [
      "Generado por el Stack Builder de AltFreeStack — altfreestack.com/stacks/builder",
      "",
      "Qué hace este script:",
      "  1. Comprueba si Docker está instalado; si no, lo instala con el script oficial de Docker.",
      "  2. Crea la carpeta del proyecto y guarda ahí el docker-compose.yml fusionado",
      "     (con los puertos ya resueltos y secretos aleatorios ya generados).",
      "  3. Arranca los contenedores con \"docker compose up -d\".",
      "No toca nada fuera de esa carpeta ni de la instalación de Docker.",
    ],
    alreadyExists: (dir) => `⚠️  Ya existe ${dir} — no se sobrescribe nada.`,
    alreadyExistsHint: (dir) => `   Si quieres reinstalar, muévela o bórrala primero: rm -rf ${dir}`,
    checkingDocker: "→ Docker no está instalado. Instalando con el script oficial...",
    startingContainers: "→ Arrancando los contenedores...",
    successBanner: "🎉 ¡Tu Stack está funcionando con éxito!",
    filesSavedAt: "📁 Archivos guardados en:",
    notIncluded: "No incluidas (se instalan por script aparte):",
    composeHeader: (names) => [
      "# docker-compose.yml generado por el Stack Builder de AltFreeStack",
      `# Combina: ${names}`,
      "# Los secretos ya se generaron aleatoriamente al ejecutar este script — no hace falta cambiar nada a mano.",
    ],
  },
  en: {
    header: [
      "Generated by AltFreeStack's Stack Builder — altfreestack.com/en/stacks/builder",
      "",
      "What this script does:",
      "  1. Checks whether Docker is installed; if not, installs it with Docker's official script.",
      "  2. Creates the project folder and saves the merged docker-compose.yml there",
      "     (ports already resolved, random secrets already generated).",
      "  3. Starts the containers with \"docker compose up -d\".",
      "Doesn't touch anything outside that folder or the Docker install.",
    ],
    alreadyExists: (dir) => `⚠️  ${dir} already exists — nothing was overwritten.`,
    alreadyExistsHint: (dir) => `   To reinstall, move or remove it first: rm -rf ${dir}`,
    checkingDocker: "→ Docker isn't installed. Installing it with the official script...",
    startingContainers: "→ Starting the containers...",
    successBanner: "🎉 Your stack is up and running!",
    filesSavedAt: "📁 Files saved to:",
    notIncluded: "Not included (install separately via their own script):",
    composeHeader: (names) => [
      "# docker-compose.yml generated by AltFreeStack's Stack Builder",
      `# Combines: ${names}`,
      "# Secrets were already generated randomly by this script — nothing to change by hand.",
    ],
  },
};

/** Escapa comillas dobles para insertar texto dentro de un `echo "..."` de bash. */
function shEscape(text: string): string {
  return text.replace(/(["\\$`])/g, "\\$1");
}

export function buildDeployScript({
  yaml,
  toolSummaries,
  skippedTools,
  locale = "es",
}: {
  yaml: string;
  toolSummaries: StackMergeToolSummary[];
  skippedTools: string[];
  locale?: "es" | "en";
}): string {
  const t = STRINGS[locale];
  const appDir = "$HOME/altfreestack-app";

  // mergeDockerComposeFiles() antepone un comentario de cabecera que
  // literalmente menciona el texto "change-me..." como documentación — si
  // randomizeSecrets() se aplicara sobre el YAML completo, ese propio
  // comentario quedaría "aleatorizado" también (falso positivo del regex).
  // Por eso aquí se sustituye esa cabecera por una propia para el contexto
  // de despliegue en 1 comando, y solo se aleatoriza el cuerpo real
  // (services/volumes) a partir de "services:".
  const bodyStart = yaml.indexOf("services:");
  const body = bodyStart >= 0 ? yaml.slice(bodyStart) : yaml;
  const toolNames = toolSummaries.map((tool) => tool.name).join(", ");
  const finalYaml = [...t.composeHeader(toolNames), "", randomizeSecrets(body)].join("\n");
  const delimiter = pickHeredocDelimiter(finalYaml);

  const summaryLines = toolSummaries.map((tool) =>
    tool.port
      ? `echo "• ${shEscape(tool.name)}:  http://$IP:${tool.port}"`
      : `echo "• ${shEscape(tool.name)}"`
  );

  const skippedLines =
    skippedTools.length > 0
      ? [`echo ""`, `echo "${shEscape(t.notIncluded)} ${shEscape(skippedTools.join(", "))}"`]
      : [];

  const lines = [
    "#!/usr/bin/env bash",
    ...t.header.map((line) => (line ? `# ${line}` : "#")),
    "",
    "set -euo pipefail",
    "",
    `APP_DIR="${appDir}"`,
    "",
    'if [ -d "$APP_DIR" ]; then',
    // Sin shEscape aquí a propósito: el texto incluye "$APP_DIR" como
    // referencia real a la variable de shell (para que se expanda a la ruta
    // real al imprimirse), no como dato externo que haya que neutralizar.
    `  echo "${t.alreadyExists("$APP_DIR")}"`,
    `  echo "${t.alreadyExistsHint("$APP_DIR")}"`,
    "  exit 1",
    "fi",
    "",
    "if ! command -v docker >/dev/null 2>&1; then",
    `  echo "${shEscape(t.checkingDocker)}"`,
    "  curl -fsSL https://get.docker.com | sh",
    "fi",
    "",
    'mkdir -p "$APP_DIR"',
    `cat > "$APP_DIR/docker-compose.yml" <<'${delimiter}'`,
    finalYaml,
    delimiter,
    "",
    `echo "${shEscape(t.startingContainers)}"`,
    'cd "$APP_DIR"',
    "docker compose up -d",
    "",
    'IP=$(curl -s -4 --max-time 5 ifconfig.me 2>/dev/null || echo "TU_IP")',
    "",
    'echo ""',
    'echo "================================================="',
    `echo "${shEscape(t.successBanner)}"`,
    'echo "-------------------------------------------------"',
    ...summaryLines,
    ...skippedLines,
    'echo "-------------------------------------------------"',
    `echo "${shEscape(t.filesSavedAt)} $APP_DIR"`,
    'echo "================================================="',
    "",
  ];

  return lines.join("\n");
}
