/**
 * Dominios de las herramientas SaaS que catalogamos como "a reemplazar".
 * Se usan solo para pedir su favicon público (ver LogoImage) — no alojamos
 * ni distribuimos ningún logo nosotros mismos.
 */
export const saasDomains: Record<string, string> = {
  Notion: "notion.so",
  Slite: "slite.com",
  Jira: "atlassian.com",
  Asana: "asana.com",
  Linear: "linear.app",
  Trello: "trello.com",
  Airtable: "airtable.com",
  "Google Analytics": "analytics.google.com",
  Mixpanel: "mixpanel.com",
  Amplitude: "amplitude.com",
  Calendly: "calendly.com",
  Slack: "slack.com",
  "Microsoft Teams": "microsoft.com",
  Salesforce: "salesforce.com",
  HubSpot: "hubspot.com",
  Intercom: "intercom.com",
  Zendesk: "zendesk.com",
  Firebase: "firebase.google.com",
  "Amazon S3": "aws.amazon.com",
  "Google Drive": "drive.google.com",
  Dropbox: "dropbox.com",
  Zapier: "zapier.com",
  Make: "make.com",
  "ChatGPT Plus": "openai.com",
  "Datadog LLM Observability": "datadoghq.com",
  Confluence: "atlassian.com",
  Todoist: "todoist.com",
  Evernote: "evernote.com",
  OneNote: "microsoft.com",
  "Google Docs": "google.com",
  Canny: "canny.io",
  Doodle: "doodle.com",
  "MS Project": "microsoft.com",
  Looker: "looker.com",
  Tableau: "tableau.com",
  "Power BI": "powerbi.microsoft.com",
  FullStory: "fullstory.com",
  LogRocket: "logrocket.com",
  GitHub: "github.com",
  CircleCI: "circleci.com",
  "Docker Desktop": "docker.com",
  Contentful: "contentful.com",
  "AWS AppSync": "aws.amazon.com",
  Algolia: "algolia.com",
  OneSignal: "onesignal.com",
  Retool: "retool.com",
  LaunchDarkly: "launchdarkly.com",
  Mailchimp: "mailchimp.com",
  DocuSign: "docusign.com",
  UptimeRobot: "uptimerobot.com",
  Pingdom: "pingdom.com",
  Datadog: "datadoghq.com",
  "Zoho CRM": "zoho.com",
  Clay: "clay.com",
  "Help Scout": "helpscout.com",
  "OpenAI API": "openai.com",
  Midjourney: "midjourney.com",
  Voiceflow: "voiceflow.com",
  Dialogflow: "cloud.google.com",
  Typeform: "typeform.com",
  "Perplexity AI": "perplexity.ai",
  "Bolt.new": "bolt.new",
  "Google Photos": "photos.google.com",
  "Google Search": "google.com",
  Shopify: "shopify.com",
  BigCommerce: "bigcommerce.com",
  "Shopify Plus": "shopify.com",
  Magento: "adobe.com",
  Zoom: "zoom.us",
  "Google Meet": "meet.google.com",
  Skype: "skype.com",
  "Twilio Video": "twilio.com",
  "1Password": "1password.com",
  LastPass: "lastpass.com",
  "1Password Business": "1password.com",
  "LastPass Teams": "lastpass.com",
};

export function getSaasDomain(name: string): string | undefined {
  return saasDomains[name];
}
