import { isComposeFile } from "@/lib/deploy-guide";

/** Únicos 2 mensajes que este módulo genera — nunca texto libre, así que localizarlos aquí no duplica ningún string ya presente en los diccionarios de i18n/. */
const MERGE_STRINGS = {
  es: {
    portReassigned: (toolName: string, hostPort: string, finalPort: string) =>
      `${toolName}: puerto ${hostPort} ya usado por otra herramienta del stack → reasignado a ${finalPort}.`,
    renamed: (toolName: string, parts: string) => `${toolName}: renombrado(s) por colisión con otra herramienta del stack — ${parts}.`,
    header: (names: string) => [
      "# docker-compose.yml generado por el Stack Builder de AltFreeStack",
      `# Combina: ${names}`,
      '# Antes de arrancar, sustituye cada valor "change-me..." por un secreto real',
      '# (usa el botón "Generar secretos seguros" de la ficha de cada herramienta).',
      "",
      "services:",
    ],
  },
  en: {
    portReassigned: (toolName: string, hostPort: string, finalPort: string) =>
      `${toolName}: port ${hostPort} already used by another tool in the stack → reassigned to ${finalPort}.`,
    renamed: (toolName: string, parts: string) => `${toolName}: renamed due to a collision with another tool in the stack — ${parts}.`,
    header: (names: string) => [
      "# docker-compose.yml generated by AltFreeStack's Stack Builder",
      `# Combines: ${names}`,
      '# Before starting, replace every "change-me..." value with a real secret',
      '# (use the "Generate secure secrets" button on each tool\'s page).',
      "",
      "services:",
    ],
  },
} as const;

interface ParsedBlock {
  name: string;
  bodyLines: string[];
}

interface ParsedCompose {
  services: ParsedBlock[];
  volumes: ParsedBlock[];
}

/**
 * Parser deliberadamente ingenuo (no un parser YAML real) — se apoya en que
 * TODO el catálogo de AltFreeStack se escribe con el mismo estilo consistente:
 * `services:`/`volumes:` en columna 0, cada entrada con exactamente 2
 * espacios de indentación y sin valor en la misma línea. Verificado contra
 * el catálogo completo (ningún docker-compose.yml usa `networks:` ni
 * variantes de indentación). Si algún día se añade una herramienta con un
 * compose.yml de forma distinta, el fusionador la trata como no fusionable
 * (mergeDockerComposeFiles la añade a `skippedTools`) en vez de generar un
 * archivo incorrecto.
 */
function parseCompose(text: string): ParsedCompose {
  const lines = text.split("\n");
  const services: ParsedBlock[] = [];
  const volumes: ParsedBlock[] = [];
  let mode: "none" | "services" | "volumes" = "none";
  let current: ParsedBlock | null = null;

  const flush = () => {
    if (!current) return;
    if (mode === "services") services.push(current);
    else if (mode === "volumes") volumes.push(current);
    current = null;
  };

  for (const line of lines) {
    if (/^services:\s*$/.test(line)) {
      flush();
      mode = "services";
      continue;
    }
    if (/^volumes:\s*$/.test(line)) {
      flush();
      mode = "volumes";
      continue;
    }
    if (/^\S/.test(line) && line.trim() !== "") {
      // Volvimos a un nivel superior (0 espacios) con otra clave que no
      // manejamos (ej. "version:") — cierra la sección actual.
      flush();
      mode = "none";
      continue;
    }
    if (mode === "none") continue;
    const headerMatch = line.match(/^ {2}([A-Za-z0-9_.-]+):\s*$/);
    if (headerMatch) {
      flush();
      current = { name: headerMatch[1], bodyLines: [] };
      continue;
    }
    if (current) current.bodyLines.push(line);
  }
  flush();

  return { services, volumes };
}

/** Reescribe `depends_on:\n  - nombre` cuando `nombre` fue renombrado por colisión. */
function rewriteDependsOn(bodyLines: string[], renameMap: Map<string, string>): string[] {
  if (renameMap.size === 0) return bodyLines;
  return bodyLines.map((line) => {
    const m = line.match(/^(\s*-\s*)([A-Za-z0-9_.-]+)\s*$/);
    if (m && renameMap.has(m[2])) return `${m[1]}${renameMap.get(m[2])}`;
    return line;
  });
}

/** Reescribe montajes `- nombre_volumen:/ruta` cuando el volumen fue renombrado por colisión. */
function rewriteVolumeMounts(bodyLines: string[], volumeRenameMap: Map<string, string>): string[] {
  if (volumeRenameMap.size === 0) return bodyLines;
  return bodyLines.map((line) => {
    const m = line.match(/^(\s*-\s*)([A-Za-z0-9_.-]+)(:\/.*)$/);
    if (m && volumeRenameMap.has(m[2])) return `${m[1]}${volumeRenameMap.get(m[2])}${m[3]}`;
    return line;
  });
}

/**
 * Reasigna el puerto de host de una línea `- "HOST:CONTAINER"` si ya está en
 * uso por otra herramienta del stack. `firstPort` recibe el primer puerto de
 * host visto en este bloque (ya con la reasignación aplicada), para poder
 * imprimir un resumen "herramienta → URL" después de fusionar.
 */
function rewritePorts(
  bodyLines: string[],
  usedHostPorts: Set<string>,
  warnings: string[],
  toolName: string,
  firstPort: { value: string | null },
  strings: (typeof MERGE_STRINGS)["es"]
): string[] {
  return bodyLines.map((line) => {
    const m = line.match(/^(\s*-\s*)"?(\d{2,5}):(\d{1,5}(?:\/(?:tcp|udp))?)"?\s*$/);
    if (!m) return line;
    const [, prefix, hostPort, rest] = m;
    let finalPort = hostPort;
    if (usedHostPorts.has(finalPort)) {
      let candidate = parseInt(hostPort, 10) + 1;
      while (usedHostPorts.has(String(candidate))) candidate++;
      finalPort = String(candidate);
      warnings.push(strings.portReassigned(toolName, hostPort, finalPort));
    }
    usedHostPorts.add(finalPort);
    if (!firstPort.value) firstPort.value = finalPort;
    return `${prefix}"${finalPort}:${rest}"`;
  });
}

export interface StackMergeInput {
  slug: string;
  name: string;
  dockerCompose: string;
}

export interface StackMergeToolSummary {
  name: string;
  slug: string;
  /** Primer puerto de host detectado para esta herramienta, ya con la reasignación por colisión aplicada — null si no se encontró ninguno. */
  port: string | null;
}

export interface StackMergeResult {
  /** El docker-compose.yml combinado, listo para `docker compose up -d`. Vacío si ninguna herramienta era fusionable. */
  yaml: string;
  /** Avisos legibles (renombrados, puertos reasignados) para mostrar al usuario — nunca se ocultan. */
  warnings: string[];
  /** Nombres de herramientas sin docker-compose.yml combinable (instaladores por script) — no entran en el archivo. */
  skippedTools: string[];
  /** Una entrada por herramienta incluida en el archivo, en el mismo orden — para imprimir un resumen "herramienta → URL". */
  toolSummaries: StackMergeToolSummary[];
}

export function mergeDockerComposeFiles(tools: StackMergeInput[], locale: "es" | "en" = "es"): StackMergeResult {
  const strings = MERGE_STRINGS[locale];
  const usedServiceNames = new Set<string>();
  const usedVolumeNames = new Set<string>();
  const usedHostPorts = new Set<string>();
  const warnings: string[] = [];
  const skippedTools: string[] = [];
  const serviceLines: string[] = [];
  const volumeLines: string[] = [];
  const toolSummaries: StackMergeToolSummary[] = [];

  for (const tool of tools) {
    if (!tool.dockerCompose || !isComposeFile(tool.dockerCompose)) {
      skippedTools.push(tool.name);
      continue;
    }

    const { services, volumes } = parseCompose(tool.dockerCompose);
    if (services.length === 0) {
      skippedTools.push(tool.name);
      continue;
    }

    const firstPort: { value: string | null } = { value: null };

    const renameMap = new Map<string, string>();
    const volumeRenameMap = new Map<string, string>();
    const finalServiceNames = new Map<string, string>();
    const finalVolumeNames = new Map<string, string>();

    for (const svc of services) {
      let finalName = svc.name;
      if (usedServiceNames.has(finalName)) {
        finalName = `${tool.slug}-${svc.name}`;
        let suffix = 2;
        while (usedServiceNames.has(finalName)) finalName = `${tool.slug}-${svc.name}-${suffix++}`;
        renameMap.set(svc.name, finalName);
      }
      usedServiceNames.add(finalName);
      finalServiceNames.set(svc.name, finalName);
    }

    for (const vol of volumes) {
      let finalName = vol.name;
      if (usedVolumeNames.has(finalName)) {
        finalName = `${tool.slug}-${vol.name}`;
        let suffix = 2;
        while (usedVolumeNames.has(finalName)) finalName = `${tool.slug}-${vol.name}-${suffix++}`;
        volumeRenameMap.set(vol.name, finalName);
      }
      usedVolumeNames.add(finalName);
      finalVolumeNames.set(vol.name, finalName);
    }

    if (renameMap.size > 0 || volumeRenameMap.size > 0) {
      const parts = [...renameMap.entries(), ...volumeRenameMap.entries()].map(([from, to]) => `"${from}" → "${to}"`);
      warnings.push(strings.renamed(tool.name, parts.join(", ")));
    }

    serviceLines.push(`  # ── ${tool.name} ──`);
    for (const svc of services) {
      const finalName = finalServiceNames.get(svc.name)!;
      let body = rewriteDependsOn(svc.bodyLines, renameMap);
      body = rewriteVolumeMounts(body, volumeRenameMap);
      body = rewritePorts(body, usedHostPorts, warnings, tool.name, firstPort, strings);
      serviceLines.push(`  ${finalName}:`, ...body, "    networks:", "      - altfreestack-net");
    }

    for (const vol of volumes) {
      const finalName = finalVolumeNames.get(vol.name)!;
      volumeLines.push(`  ${finalName}:`, ...vol.bodyLines);
    }

    toolSummaries.push({ name: tool.name, slug: tool.slug, port: firstPort.value });
  }

  if (serviceLines.length === 0) {
    return { yaml: "", warnings, skippedTools, toolSummaries };
  }

  const header = strings.header(tools.filter((t) => !skippedTools.includes(t.name)).map((t) => t.name).join(", "));

  const body = [...header, ...serviceLines];
  if (volumeLines.length > 0) {
    body.push("", "volumes:", ...volumeLines);
  }
  body.push("", "networks:", "  altfreestack-net:", "    driver: bridge");

  return { yaml: body.join("\n"), warnings, skippedTools, toolSummaries };
}
